import { createLogEntry } from "./logger";
import type { LogEntry } from "./types";

const timestamp = "2026-08-09T12:00:00.000Z";

export const MARKER_LOG_EXAMPLES: readonly LogEntry[] = [
  createLogEntry({
    durationMs: 12.34,
    event: "capability.detected",
    input: { secureContext: true, userAgent: "Chrome" },
    level: "info",
    marker: "[CAPABILITY]",
    output: { actions: [], capabilities: [] },
    scope: "editor-bootstrap",
    timestamp,
  }),
  createLogEntry({
    event: "execution.completed",
    input: { beforeRevision: 11, command: "clip.move" },
    level: "info",
    marker: "[COMMAND]",
    output: { afterRevision: 12, transactionId: "tx_12" },
    projectRevision: 12,
    requestId: "cmd_12",
    scope: "command-bus",
    timestamp,
  }),
  createLogEntry({
    durationMs: 42,
    event: "probe.completed",
    input: { name: "test_2.mp4", size: 911_401_782 },
    level: "info",
    marker: "[IMPORT]",
    output: { durationSec: 3_207.93, video: "avc1.640028" },
    requestId: "import_01",
    scope: "media-worker",
    timestamp,
  }),
  createLogEntry({
    event: "cache.hit",
    input: { cacheKey: "asset_01:proxy-540p" },
    level: "info",
    marker: "[PROXY]",
    output: { bytes: 18_420_331 },
    requestId: "proxy_01",
    scope: "media-worker",
    timestamp,
  }),
  createLogEntry({
    event: "request",
    input: { timeSec: 18.4 },
    level: "debug",
    marker: "[SEEK]",
    projectRevision: 12,
    requestId: "seek_42",
    scope: "scheduler",
    timestamp,
  }),
  createLogEntry({
    event: "packet",
    input: { timeSec: 18.4 },
    level: "debug",
    marker: "[DEMUX]",
    output: new Uint8Array([0, 0, 0, 1, 103]),
    projectRevision: 12,
    requestId: "seek_42",
    scope: "media-worker",
    timestamp,
  }),
  createLogEntry({
    event: "frame",
    input: { packetTimestampUs: 18_400_000 },
    level: "debug",
    marker: "[DECODE]",
    output: { height: 540, timestampUs: 18_400_000, width: 960 },
    projectRevision: 12,
    requestId: "seek_42",
    scope: "media-worker",
    timestamp,
  }),
  createLogEntry({
    durationMs: 1.2,
    event: "waveform.completed",
    input: new Float32Array([0.1, -0.2, 0.3]),
    level: "info",
    marker: "[WASM]",
    output: { buckets: 1 },
    requestId: "waveform_01",
    scope: "wasm-wrapper",
    timestamp,
  }),
  createLogEntry({
    event: "evaluate",
    input: { playheadSec: 18.4 },
    level: "debug",
    marker: "[ECS]",
    output: { visibleEntities: 2 },
    projectRevision: 12,
    requestId: "seek_42",
    scope: "preview-runtime",
    timestamp,
  }),
  createLogEntry({
    event: "present",
    input: { frameTimestampUs: 18_400_000 },
    level: "debug",
    marker: "[RENDER]",
    output: { height: 540, width: 960 },
    projectRevision: 12,
    requestId: "seek_42",
    scope: "preview-renderer",
    timestamp,
  }),
  createLogEntry({
    durationMs: 8_420,
    event: "completed",
    input: { fps: 30, source: "original" },
    level: "info",
    marker: "[EXPORT]",
    output: { bytes: 18_420_331, frames: 300, mimeType: "video/mp4" },
    projectRevision: 17,
    requestId: "export_01",
    scope: "export-worker",
    timestamp,
  }),
  createLogEntry({
    event: "summary",
    input: { path: "/test_assets/test_1.mp4" },
    level: "info",
    marker: "[PROBE]",
    output: { audio: "aac", height: 720, video: "h264", width: 720 },
    requestId: "probe_01",
    scope: "probe-cli",
    timestamp,
  }),
];

export const SEEK_TRACE_EXAMPLE = MARKER_LOG_EXAMPLES.filter(
  (entry) => entry.requestId === "seek_42",
);
